export declare const isPojo: (obj: any) => boolean;
export declare const isDev: boolean;
export declare const debug: (key: string, ...args: any[]) => void;
export declare function set<S>(to: S, from: Partial<S>): S;
export declare function merge<S>(to: S, from: Partial<S>): S;
export declare function clone<S>(from: S): S;
export declare function setDeep<S, V>(path: string[], value: V, from: S): S;
export declare function setDeepMutable<S, V>(path: string[], value: V, from: S): S;
export declare function get(path: string[], from: any, len?: number): any;
export declare function isFn(data: any): data is Function;
export declare const noop: (f: any) => any;
