export declare const isPojo: (obj: any) => boolean;
export declare const isDev: boolean;
export declare const debug: (key: string, ...args: any[]) => void;
export declare function set(to: any, from: any): any;
export declare function merge(to: any, from: any): any;
export declare function clone(from: any): any;
export declare function setDeep(path: string[], value: any, from: any): any;
export declare function setDeepMutable(path: string[], value: any, from: any): any;
export declare function get(path: string[], from: any, len?: number): any;
export declare function isFn(data: any): data is Function;
export declare const noop: (f: any) => any;
